from __future__ import annotations

import json
import re
from pathlib import Path

from .config import BY_WORKFLOW_ROOT, GENERATED_ROOT


_METADATA_FIELDS = ("note_urls", "node_types", "sources")


def _parse_comment_payload(raw: str, prefix: str) -> tuple[str, str] | None:
    if not raw.startswith(prefix):
        return None
    payload = raw[len(prefix):].strip()
    if ":" not in payload:
        return None
    model_name, value = payload.split(":", 1)
    model_name = model_name.strip()
    value = value.strip()
    if not model_name:
        return None
    return model_name, value


def _entry_metadata(entry: dict) -> dict:
    metadata = {}
    for key in _METADATA_FIELDS:
        value = entry.get(key)
        if value:
            metadata[key] = value
    return metadata


def _safe_workflow_filename(workflow_name: str) -> str:
    raw = str(workflow_name or "").strip()
    raw = raw.replace("\\", "/").split("/")[-1].strip()
    raw = re.sub(r"^[*•\s]+", "", raw)
    raw = re.sub(r'[<>:"/\\|?*\x00-\x1F]', "_", raw)
    raw = raw.rstrip(" .")
    return raw or "current-workflow.json"


def manifest_path_for_workflow(workflow_name: str) -> Path:
    safe_name = _safe_workflow_filename(workflow_name)
    return BY_WORKFLOW_ROOT / f"{safe_name}.manifest.txt"


def runtime_manifest_path(workflow_name: str) -> Path:
    safe_name = _safe_workflow_filename(workflow_name)
    return GENERATED_ROOT / f"{safe_name}.runtime.manifest.txt"


def parse_manifest(path: Path) -> list[dict]:
    if not path.exists():
        return []

    entries_by_model: dict[str, dict] = {}
    notes_by_model: dict[str, str] = {}
    metadata_by_model: dict[str, dict] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line:
            continue
        if line.startswith("# NOTE:"):
            payload = _parse_comment_payload(line, "# NOTE:")
            if payload:
                model_name, note = payload
                notes_by_model[model_name] = note
            continue
        if line.startswith("# META:"):
            payload = _parse_comment_payload(line, "# META:")
            if payload:
                model_name, encoded = payload
                try:
                    parsed = json.loads(encoded)
                except json.JSONDecodeError:
                    parsed = {}
                if isinstance(parsed, dict):
                    metadata_by_model[model_name] = parsed
            continue
        if line.startswith("#"):
            continue
        parts = [part.strip() for part in line.split("|")]
        kind = parts[0].upper()
        if kind == "INCLUDE":
            continue
        if len(parts) < 3:
            continue
        source = parts[1]
        target = parts[2]
        target_path = Path(target)
        model_name = Path(target).name
        candidate = {
            "kind": kind,
            "source": source,
            "target": target,
            "model_name": model_name,
            "category": target_path.parent.as_posix() if str(target_path.parent) not in {"", "."} else "other",
            "resolved": bool(source and not source.upper().startswith("PASTE_")),
        }
        note = notes_by_model.get(model_name)
        if note:
            candidate["note"] = note
        metadata = metadata_by_model.get(model_name) or {}
        for key in _METADATA_FIELDS:
            value = metadata.get(key)
            if value:
                candidate[key] = value
        existing = entries_by_model.get(model_name)
        if existing is None:
            entries_by_model[model_name] = candidate
            continue
        if candidate["resolved"] and not existing["resolved"]:
            entries_by_model[model_name] = candidate
            continue
        if candidate["resolved"] == existing["resolved"] and len(candidate["target"]) < len(existing["target"]):
            entries_by_model[model_name] = candidate
    return list(entries_by_model.values())


def write_manifest(path: Path, workflow_name: str, entries: list[dict]) -> Path:
    lines = [
        f"# Workflow: {workflow_name}",
        f"# Manifest: {path.name}",
        "# Generated by Workflow Asset Agent.",
        "",
    ]
    for entry in entries:
        note = (entry.get("note") or "").strip()
        if note:
            lines.append(f"# NOTE: {entry['model_name']}: {note}")
        metadata = _entry_metadata(entry)
        if metadata:
            lines.append(
                f"# META: {entry['model_name']}: {json.dumps(metadata, ensure_ascii=True, sort_keys=True)}"
            )
        lines.append(f"{entry['kind'].upper()}|{entry['source']}|{entry['target']}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path
